title: Random Access Memory
author: Ram Vishnampet
tagline: Ram's Blog
description: >-
  Welcome to Ram's blog. I write technical articles on DevOps, software
  architecture, and data science. I code in Python, Typescript and C++.
baseurl: ""
email: rvishnampet@gmail.com
url: "https://rvishna.github.io"

theme: minima
strict_front_matter: true
plugins:
  - jekyll-feed
  - jekyll-seo-tag
  - jekyll-sitemap

twitter_username: rvishnampet
github_username: rvishna

show_excerpts: true

markdown: kramdown
