title: Random Access Memory
tagline: Ram's Blog
author:
  name: Ram Vishnampet
  email: rvishnampet@gmail.com
description: >-
  Welcome to Ram's blog. I write technical articles on DevOps, software
  architecture, and data science. I code in Python, Typescript and C++.
baseurl: ""
url: "https://rvishna.github.io"

theme: minima
strict_front_matter: true
plugins:
  - jekyll-feed
  - jekyll-seo-tag
  - jekyll-sitemap

minima:
  social_links:
    twitter: rvishnampet
    github: rvishna
    linkedin: ramanathan-vishnampet-350a0561

show_excerpts: true

markdown: kramdown
